version: 2.1

jobs:
  build:
    parameters:
      jdk:
        type: string
      mvnOptions:
        type: string
    working_directory: ~/named-regexp-ci
    docker:
      - image: adoptopenjdk/maven-openjdk<<parameters.jdk>>
    steps:
      - checkout
      - restore_cache:
          key: named-regexp-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: named-regexp-{{ checksum "pom.xml" }}
      - run: mvn verify -Dgpg.skip <<parameters.mvnOptions>>
      - store_test_results:
          path: target/surefire-reports
#      - store_artifacts:
#          path: target/named-regexp*.*

workflows:
  maven_test:
    jobs:
      - build:
          matrix:
            parameters:
              jdk: ['8', '9', '10', '11']
              mvnOptions: '-Dmaven.compiler.source=6 -Dmaven.compiler.target=6'
      - build:
          matrix:
            parameters:
              jdk: ['12', '13']
              # JDK12+ no longer supports JDK6 as source/target
              mvnOptions: '-Dmaven.compiler.source=7 -Dmaven.compiler.target=7'
