version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test:
          matrix:
            parameters:
              executor: ['8.0', '11.0', '12.0', '13.0', '14.0']
              command: ['verify -Dgpg.skip']
