version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test
        matrix:
          executor: ['8.0.242', '11.0.7', '12.0.2', '13.0.2', '14.0.1']
          command: ['verify -Dgpg.skip']
