version: 2.1

jobs:
  build:
    parameters:
      jdk:
        type: string
    working_directory: ~/named-regexp-ci
    docker:
      - image: adoptopenjdk/openjdk<<parameters.jdk>>
    steps:
      - checkout
      - restore_cache:
          key: named-regexp-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: named-regexp-{{ checksum "pom.xml" }}
      - run: mvn verify -Dgpg.skip
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/named-regexp*.*

workflows:
  maven_test:
    jobs:
      - build:
          matrix:
            parameters:
              jdk: ['8', '9', '10', '11', '12', '13', '14']
