name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-8-11:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        jdk: [ '8', '9', '10', '11' ]
    name: JDK ${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}
          cache: 'maven'
      - run: mvn verify -Dgpg.skip -Dmaven.compiler.source=6 -Dmaven.compiler.target=6

  # JDK12+ no longer supports JDK6 as source/target
  build-12-plus:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        jdk: [ '12', '13', '14', '15', '16', '17', '18', '19', '20', '21' ]
    name: JDK ${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}
          cache: 'maven'
      - run: mvn verify -Dgpg.skip -Dmaven.compiler.source=7 -Dmaven.compiler.target=7