name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-6:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        jdk: [ '6' ]
    name: JDK ${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}
      - run: mvn verify -Dgpg.skip

  build-7-11:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        jdk: [ '7', '8', '9', '10', '11' ]
    name: JDK ${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: ${{ matrix.jdk }}
          cache: 'maven'
      - run: mvn verify -Dgpg.skip -Dmaven.compiler.source=6 -Dmaven.compiler.target=6

  # JDK12+ no longer supports JDK6 as source/target
  build-12-plus:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        jdk: [ '12', '13', '14', '15', '16', '17', '18' ]
    name: JDK ${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}
          cache: 'maven'
      - run: mvn verify -Dgpg.skip -Dmaven.compiler.source=7 -Dmaven.compiler.target=7