name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-legacy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        jdk: [ '8', '11' ]
    name: JDK ${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
          cache: 'maven'
      - run: mvn verify -Dgpg.skip -Dmaven.compiler.source=6 -Dmaven.compiler.target=6

  # JDK12+ no longer supports JDK6 as source/target
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        jdk: [ '16', '17', '18' ]
    name: JDK ${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
          cache: 'maven'
      - run: mvn verify -Dgpg.skip -Dmaven.compiler.source=7 -Dmaven.compiler.target=7